# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
